project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "In-Class Exercise 4"
            href: "In-Class_Ex/In-Class_Ex_04/In-Class_Ex_04.html"  
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-Home-Exercise/Take-Home-Exercise_01.html"
          - text: "Take-home Exercise 2"
            href: "Take-Home-Exercise/Take-Home-Exercise_02.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

