---
title: "Hands-on Exercise 7"
---

```{r}
pacman::p_load(tmap, tidyverse, sf)
sgpools <- read_csv("data/SGPools_svy21.csv")
head(sgpools)
```

```{r}
sgpools_sf <- st_as_sf(sgpools, coords = c("XCOORD", "YCOORD"),
                       crs=3414) # 3414 makes tmap know which projection we are using. Coordinate Reference SyStem.

```

```{r}
 # to create an interactive viewing mode
tmap_mode("view")
tm_shape(sgpools_sf)+
  tm_bubbles(col="red",
             size=1,
             border.col="black",
             border.lwd=1
               )
tmap_mode("plot")

```

```{r}

popdata <- read_csv("data/respopagesextod2011to2020.csv")

popdata2020 <- popdata %>%
  filter(Time==2020) %>%
  group_by(PA, SZ, AG) %>%
  summarise(`POP` = sum(`Pop`)) %>%
  ungroup() %>%
  pivot_wider(names_from=AG,
              values_from=POP) %>%
  mutate(`YOUNG`=rowSums(.[3:6])) 
  + rowSums(.[12]) %>%
  mutate(`ECONOMY ACTIVE` = rowSums(.[7:11]))
  + rowSums(.[13:15])%>%
  mutate(`AGED`=rowSums(.[16:21]))
  + rowSums(.[17])


```

```{r}
popdata2020 <- popdata2020 %>%
  mutate_at(.vars=vars(PA,SZ),
            .funs=funs(toupper)) %>%
  filter(`ECONOMY ACTIVE`>0)
```

```{r}

```

```{r}

```
